label SceneOne:
    "Meeting with your advisors should be classified as a type of torture, in my opinion."
    Advisor "And of course, we need to do something about your… ehem—{w=0.75} outfit, princess Calliope. For the ball."
    "Yeah.{w} Torture."
    Advisor "A princess you may be, but you certainly aren't a fan of bureaucracy in any form."
    "You know that you have to know this, but that doesn't make it any easier to sit through, especially when the advisors have it out for you"
    "'Too precocious,{w=0.75} too reckless,{w=0.75} too masculine.{w=0.75}' You could repeat him word for word. They're all stuffy and ridiculous, leftovers from your parent's time ruling that they handed over to you"
    "As soon as you're able, you plan to fire them."
    "You're grateful to your parents,{w=0.75} you are! But the world is getting bigger and brighter, and these advisors are definitely stuck in the past. It's unbearable to listen to, but you only have to deal with it until you turn twenty one."
    "Succeeding the throne has never looked so appealing."
    "And it's not all bad. The fact that your knight is waiting just outside the door makes everything slightly more bearable. As soon as you're safely within the walls of your room, you both are going to complain up a storm."
    "Muse has only been your personal guard for three years, but she's ambitious and smart. She makes silly faces with you when you walk the halls between meetings, and doesn't even tell your mother and father when you climb trees and fall wrong."
    "She's great, really."
    "With how she acts, honestly you'd think she was the princess."
    "She's got more decorum than you do, though that never bothered you, and she dresses like she grabbed all her outfits from your mother's closet as a young adult. People who are coming in from outside the castle often mix up who's supposed to be who."
    "It's a wonder she hasn't—{nw=0.75}"
    "CRASH" with sshake
    "There's a scuffle outside the hallway, something quick and muffled."
    "You wouldn't usually worry—{w=0.75} Muse is super duper competent!—{w=0.75} but then she lets out a muffled swear."
    Muse "FUCK— LET ME GO!" with sshake
    "Muse {i}never{/i} swears."
    "She thinks it's improper for a lady of her knightlyness to do such a thing. The last time she swore was when you almost fell off the low part of the castle roof."
    "You get up, despite shouts to stay put."
    Advisor "My lady, please stay seated while the danger is dealt with!"
    "Like hell. Muse is {i}the{/i} best guard you've ever had. You're not going to sit by and let her get killed!"
    "But by the time you get out to the hallway, advisors close behind you, Muse is gone. All that's left of her is a scrap of her dress and a note."
    "The handwriting looks ridiculous."
    "‘I have taken your very lovely princess! We are to be wed at dawn in three days time, and then I will be king of your kingdom! You're invited to the wedding if you can make it in time. Toodles!’"
    "There is so much wrong with that letter. Starting with the written out addition of 'toodles'."
    "And yeah Muse is lovely, but she's not you! You're a very pretty princess. You're almost insulted."
    "Almost, because the idea of being called lovely by this guy gives you major creeps."
    "You feel—{w} helpless. You're not used to being on this side of the kidnapping!{w} You're used to being the damsel, not the one waiting patiently for the damsel to be returned safely."
    "You don't know how your family does it, even if it's basically routine. The idea of Muse being in this stupid guy's clutches makes you itchy and frantic."
    "A realization hits. You can't sit still while Muse is dealing with a creep that's trying to marry her! If she's the princess this time, then you'll just have to be the knight."
    Advisor "Princess Calliope, what are you doing?!"
    "You run past him with a grin."
    #expression i think
    Cal "I'm going to save my knight!"
    "He sputters out denials, but you ignore him with the ease of lots of practice. You almost head straight for the armory, but pivot midway."
    "What's a knight without a friend?"
    "You knock heavily at Harper's door. Harper, your best friend since the wet nurse, opens the door, sees the look on your face, and immediately attempts to slam it shut."
    #Cg of Harper in doorway
